name = "glitch"
version = "0.0.6"
gleam = ">= 0.32.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
 description = "A Twitch client for Gleam"
 licences = ["MIT"]
 repository = { type = "github", user = "dmmulroy", repo = "glitch" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/. 

[dependencies]
gleam_stdlib = "~> 0.40.0"
logging = "~> 1.0"
gleam_json = "~> 2.0"
gleam_httpc = "~> 2.2"
gleam_http = "~> 3.6"
dot_env = "~> 0.2"
gleam_otp = "~> 0.11"
mist = "~> 2.0"
gleam_erlang = "~> 0.25"
shellout = "~> 1.6"
prng = "~> 3.0"
stratus = "~> 0.9"

[dev-dependencies]
gleeunit = "~> 1.2"
